[package]
name = "wei"
version = "0.1.5"
edition = "2021"
description = "wei system"
documentation = "https://github.com/zuiyue-com/wei"
homepage = "https://github.com/zuiyue-com/wei"
license = "MIT OR Apache-2.0"
publish = ["crates-io"]

[dependencies]


