[package]
name = "wei"
version = "0.1.3"
edition = "2021"
description = "wei system"
documentation = "https://github.com/zuiyue-com/wei"
homepage = "https://github.com/zuiyue-com/wei"
license = "MIT OR Apache-2.0"

[dependencies]


