[package]
name = "wei"
version = "0.1.5"
edition = "2021"
description = "wei system"
documentation = "https://github.com/zuiyue-com/wei"
homepage = "https://github.com/zuiyue-com/wei"
license = "MIT OR Apache-2.0"

[dependencies]
wei-run = "0.1.5"
# wei-run = { path = "../wei-run" }
wei-env = "0.2.4"

