name: Wei on Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      run: |
        choco install rust
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose